/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export interface Env {
  // Add your Cloudflare Worker environment bindings here
  // For example:
  // MY_KV_NAMESPACE: KVNamespace;
  // MY_DURABLE_OBJECT: DurableObjectNamespace;
}
