/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commissionsUpdate } from "../../funcs/commissionsUpdate.js";
import { UpdateCommissionRequest$zodSchema } from "../../models/updatecommissionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateCommissionRequest$zodSchema,
};

export const tool$commissionsUpdate: ToolDefinition<typeof args> = {
  name: "commissions-update",
  description: `Update a commission.

Update an existing commission amount. This is useful for handling refunds (partial or full) or fraudulent sales.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await commissionsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
