/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersDelete } from "../../funcs/customersDelete.js";
import { DeleteCustomerRequest$zodSchema } from "../../models/deletecustomerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCustomerRequest$zodSchema,
};

export const tool$customersDelete: ToolDefinition<typeof args> = {
  name: "customers-delete",
  description: `Delete a customer

Delete a customer from a workspace.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
