/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsUpdate } from "../../funcs/domainsUpdate.js";
import { UpdateDomainRequest$zodSchema } from "../../models/updatedomainop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateDomainRequest$zodSchema,
};

export const tool$domainsUpdate: ToolDefinition<typeof args> = {
  name: "domains-update",
  description: `Update a domain

Update a domain for the authenticated workspace.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await domainsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
