/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsRegister } from "../../funcs/domainsRegister.js";
import { RegisterDomainRequest$zodSchema } from "../../models/registerdomainop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RegisterDomainRequest$zodSchema.optional(),
};

export const tool$domainsRegister: ToolDefinition<typeof args> = {
  name: "domains-register",
  description: `Register a domain

Register a domain for the authenticated workspace. Only available for Enterprise Plans.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await domainsRegister(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
