/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { embedTokensReferrals } from "../../funcs/embedTokensReferrals.js";
import { CreateReferralsEmbedTokenRequest$zodSchema } from "../../models/createreferralsembedtokenop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateReferralsEmbedTokenRequest$zodSchema.optional(),
};

export const tool$embedTokensReferrals: ToolDefinition<typeof args> = {
  name: "embed-tokens-referrals",
  description: `Create a referrals embed token

Create a referrals embed token for the given partner/tenant.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await embedTokensReferrals(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
