/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linksDelete } from "../../funcs/linksDelete.js";
import { DeleteLinkRequest$zodSchema } from "../../models/deletelinkop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteLinkRequest$zodSchema,
};

export const tool$linksDelete: ToolDefinition<typeof args> = {
  name: "links-delete",
  description: `Delete a link

Delete a link for the authenticated workspace.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await linksDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
