/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linksList } from "../../funcs/linksList.js";
import { GetLinksRequest$zodSchema } from "../../models/getlinksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLinksRequest$zodSchema.optional(),
};

export const tool$linksList: ToolDefinition<typeof args> = {
  name: "links-list",
  description: `Retrieve a list of links

Retrieve a paginated list of links for the authenticated workspace.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await linksList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
