/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsDelete } from "../../funcs/tagsDelete.js";
import { DeleteTagRequest$zodSchema } from "../../models/deletetagop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTagRequest$zodSchema,
};

export const tool$tagsDelete: ToolDefinition<typeof args> = {
  name: "tags-delete",
  description: `Delete a tag

Delete a tag from the workspace. All existing links will still work, but they will no longer be associated with this tag.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
