/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGet } from "../../funcs/workspacesGet.js";
import { GetWorkspaceRequest$zodSchema } from "../../models/getworkspaceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetWorkspaceRequest$zodSchema,
};

export const tool$workspacesGet: ToolDefinition<typeof args> = {
  name: "workspaces-get",
  description: `Retrieve a workspace

Retrieve a workspace for the authenticated user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspacesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
