/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  RetrieveAnalyticsRequest,
  RetrieveAnalyticsRequest$zodSchema,
  RetrieveAnalyticsResponse,
  RetrieveAnalyticsResponse$zodSchema,
} from "../models/retrieveanalyticsop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Retrieve analytics for a link, a domain, or the authenticated workspace.
 *
 * @remarks
 * Retrieve analytics for a link, a domain, or the authenticated workspace. The response type depends on the `event` and `type` query parameters.
 */
export function analyticsRetrieve(
  client$: DubCore,
  request?: RetrieveAnalyticsRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    RetrieveAnalyticsResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request?: RetrieveAnalyticsRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      RetrieveAnalyticsResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => RetrieveAnalyticsRequest$zodSchema.optional().parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/analytics")();
  const query$ = encodeFormQuery({
    "browser": payload$?.browser,
    "city": payload$?.city,
    "continent": payload$?.continent,
    "country": payload$?.country,
    "customerId": payload$?.customerId,
    "device": payload$?.device,
    "domain": payload$?.domain,
    "end": payload$?.end,
    "event": payload$?.event,
    "externalId": payload$?.externalId,
    "folderId": payload$?.folderId,
    "groupBy": payload$?.groupBy,
    "interval": payload$?.interval,
    "key": payload$?.key,
    "linkId": payload$?.linkId,
    "os": payload$?.os,
    "partnerId": payload$?.partnerId,
    "programId": payload$?.programId,
    "qr": payload$?.qr,
    "referer": payload$?.referer,
    "refererUrl": payload$?.refererUrl,
    "region": payload$?.region,
    "root": payload$?.root,
    "start": payload$?.start,
    "tagId": payload$?.tagId,
    "tagIds": payload$?.tagIds,
    "tenantId": payload$?.tenantId,
    "timezone": payload$?.timezone,
    "trigger": payload$?.trigger,
    "url": payload$?.url,
    "utm_campaign": payload$?.utm_campaign,
    "utm_content": payload$?.utm_content,
    "utm_medium": payload$?.utm_medium,
    "utm_source": payload$?.utm_source,
    "utm_term": payload$?.utm_term,
  });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "retrieveAnalytics",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    RetrieveAnalyticsResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, RetrieveAnalyticsResponse$zodSchema, { key: "oneOf" }),
    M.json(400, RetrieveAnalyticsResponse$zodSchema, { key: "BadRequest" }),
    M.json(401, RetrieveAnalyticsResponse$zodSchema, { key: "Unauthorized" }),
    M.json(403, RetrieveAnalyticsResponse$zodSchema, { key: "Forbidden" }),
    M.json(404, RetrieveAnalyticsResponse$zodSchema, { key: "NotFound" }),
    M.json(409, RetrieveAnalyticsResponse$zodSchema, { key: "Conflict" }),
    M.json(410, RetrieveAnalyticsResponse$zodSchema, { key: "InviteExpired" }),
    M.json(422, RetrieveAnalyticsResponse$zodSchema, {
      key: "UnprocessableEntity",
    }),
    M.json(429, RetrieveAnalyticsResponse$zodSchema, {
      key: "RateLimitExceeded",
    }),
    M.json(500, RetrieveAnalyticsResponse$zodSchema, {
      key: "InternalServerError",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
