/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  CreateReferralsEmbedTokenRequest,
  CreateReferralsEmbedTokenRequest$zodSchema,
  CreateReferralsEmbedTokenResponse,
  CreateReferralsEmbedTokenResponse$zodSchema,
} from "../models/createreferralsembedtokenop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Create a referrals embed token
 *
 * @remarks
 * Create a referrals embed token for the given partner/tenant.
 */
export function embedTokensReferrals(
  client$: DubCore,
  request?: CreateReferralsEmbedTokenRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    CreateReferralsEmbedTokenResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request?: CreateReferralsEmbedTokenRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      CreateReferralsEmbedTokenResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) =>
      CreateReferralsEmbedTokenRequest$zodSchema.optional().parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = payload$ === undefined
    ? null
    : encodeJSON("body", payload$, { explode: true });
  const path$ = pathToFunc("/tokens/embed/referrals")();

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "createReferralsEmbedToken",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    CreateReferralsEmbedTokenResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(201, CreateReferralsEmbedTokenResponse$zodSchema, { key: "object" }),
    M.json(400, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "BadRequest",
    }),
    M.json(401, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "Unauthorized",
    }),
    M.json(403, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "Forbidden",
    }),
    M.json(404, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "NotFound",
    }),
    M.json(409, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "Conflict",
    }),
    M.json(410, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "InviteExpired",
    }),
    M.json(422, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "UnprocessableEntity",
    }),
    M.json(429, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "RateLimitExceeded",
    }),
    M.json(500, CreateReferralsEmbedTokenResponse$zodSchema, {
      key: "InternalServerError",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
