/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  BulkUpdateLinksRequest,
  BulkUpdateLinksRequest$zodSchema,
  BulkUpdateLinksResponse,
  BulkUpdateLinksResponse$zodSchema,
} from "../models/bulkupdatelinksop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Bulk update links
 *
 * @remarks
 * Bulk update up to 100 links with the same data for the authenticated workspace.
 */
export function linksUpdateMany(
  client$: DubCore,
  request?: BulkUpdateLinksRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    BulkUpdateLinksResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request?: BulkUpdateLinksRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      BulkUpdateLinksResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => BulkUpdateLinksRequest$zodSchema.optional().parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = payload$ === undefined
    ? null
    : encodeJSON("body", payload$, { explode: true });
  const path$ = pathToFunc("/links/bulk")();

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "bulkUpdateLinks",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "PATCH",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    BulkUpdateLinksResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, BulkUpdateLinksResponse$zodSchema, { key: "LinkSchemas" }),
    M.json(400, BulkUpdateLinksResponse$zodSchema, { key: "BadRequest" }),
    M.json(401, BulkUpdateLinksResponse$zodSchema, { key: "Unauthorized" }),
    M.json(403, BulkUpdateLinksResponse$zodSchema, { key: "Forbidden" }),
    M.json(404, BulkUpdateLinksResponse$zodSchema, { key: "NotFound" }),
    M.json(409, BulkUpdateLinksResponse$zodSchema, { key: "Conflict" }),
    M.json(410, BulkUpdateLinksResponse$zodSchema, { key: "InviteExpired" }),
    M.json(422, BulkUpdateLinksResponse$zodSchema, {
      key: "UnprocessableEntity",
    }),
    M.json(429, BulkUpdateLinksResponse$zodSchema, {
      key: "RateLimitExceeded",
    }),
    M.json(500, BulkUpdateLinksResponse$zodSchema, {
      key: "InternalServerError",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
