/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  BulkDeleteLinksRequest,
  BulkDeleteLinksRequest$zodSchema,
  BulkDeleteLinksResponse,
  BulkDeleteLinksResponse$zodSchema,
} from "../models/bulkdeletelinksop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Bulk delete links
 *
 * @remarks
 * Bulk delete up to 100 links for the authenticated workspace.
 */
export function linksDeleteMany(
  client$: DubCore,
  request: BulkDeleteLinksRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    BulkDeleteLinksResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request: BulkDeleteLinksRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      BulkDeleteLinksResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => BulkDeleteLinksRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/links/bulk")();
  const query$ = encodeFormQuery({
    "linkIds": payload$.linkIds,
  }, { explode: false });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "bulkDeleteLinks",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "DELETE",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    BulkDeleteLinksResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, BulkDeleteLinksResponse$zodSchema, { key: "object" }),
    M.json(400, BulkDeleteLinksResponse$zodSchema, { key: "BadRequest" }),
    M.json(401, BulkDeleteLinksResponse$zodSchema, { key: "Unauthorized" }),
    M.json(403, BulkDeleteLinksResponse$zodSchema, { key: "Forbidden" }),
    M.json(404, BulkDeleteLinksResponse$zodSchema, { key: "NotFound" }),
    M.json(409, BulkDeleteLinksResponse$zodSchema, { key: "Conflict" }),
    M.json(410, BulkDeleteLinksResponse$zodSchema, { key: "InviteExpired" }),
    M.json(422, BulkDeleteLinksResponse$zodSchema, {
      key: "UnprocessableEntity",
    }),
    M.json(429, BulkDeleteLinksResponse$zodSchema, {
      key: "RateLimitExceeded",
    }),
    M.json(500, BulkDeleteLinksResponse$zodSchema, {
      key: "InternalServerError",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
