/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeFormQuery, queryJoin } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  GetLinksRequest,
  GetLinksRequest$zodSchema,
  GetLinksResponse,
  GetLinksResponse$zodSchema,
} from "../models/getlinksop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Retrieve a list of links
 *
 * @remarks
 * Retrieve a paginated list of links for the authenticated workspace.
 */
export function linksList(
  client$: DubCore,
  request?: GetLinksRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    GetLinksResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request?: GetLinksRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      GetLinksResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => GetLinksRequest$zodSchema.optional().parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/links")();
  const query$ = queryJoin(
    encodeFormQuery({
      "tagIds": payload$?.tagIds,
      "tagNames": payload$?.tagNames,
    }, { explode: false }),
    encodeFormQuery({
      "domain": payload$?.domain,
      "folderId": payload$?.folderId,
      "page": payload$?.page,
      "pageSize": payload$?.pageSize,
      "search": payload$?.search,
      "showArchived": payload$?.showArchived,
      "sort": payload$?.sort,
      "sortBy": payload$?.sortBy,
      "sortOrder": payload$?.sortOrder,
      "tagId": payload$?.tagId,
      "tenantId": payload$?.tenantId,
      "userId": payload$?.userId,
      "withTags": payload$?.withTags,
    }),
  );

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "getLinks",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    GetLinksResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, GetLinksResponse$zodSchema, { key: "LinkSchemas" }),
    M.json(400, GetLinksResponse$zodSchema, { key: "BadRequest" }),
    M.json(401, GetLinksResponse$zodSchema, { key: "Unauthorized" }),
    M.json(403, GetLinksResponse$zodSchema, { key: "Forbidden" }),
    M.json(404, GetLinksResponse$zodSchema, { key: "NotFound" }),
    M.json(409, GetLinksResponse$zodSchema, { key: "Conflict" }),
    M.json(410, GetLinksResponse$zodSchema, { key: "InviteExpired" }),
    M.json(422, GetLinksResponse$zodSchema, { key: "UnprocessableEntity" }),
    M.json(429, GetLinksResponse$zodSchema, { key: "RateLimitExceeded" }),
    M.json(500, GetLinksResponse$zodSchema, { key: "InternalServerError" }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
