/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  RetrievePartnerAnalyticsRequest,
  RetrievePartnerAnalyticsRequest$zodSchema,
  RetrievePartnerAnalyticsResponse,
  RetrievePartnerAnalyticsResponse$zodSchema,
} from "../models/retrievepartneranalyticsop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Retrieve analytics for a partner
 *
 * @remarks
 * Retrieve analytics for a partner within a program. The response type vary based on the `groupBy` query parameter.
 */
export function partnersAnalytics(
  client$: DubCore,
  request?: RetrievePartnerAnalyticsRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    RetrievePartnerAnalyticsResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request?: RetrievePartnerAnalyticsRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      RetrievePartnerAnalyticsResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) =>
      RetrievePartnerAnalyticsRequest$zodSchema.optional().parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/partners/analytics")();
  const query$ = encodeFormQuery({
    "end": payload$?.end,
    "groupBy": payload$?.groupBy,
    "interval": payload$?.interval,
    "partnerId": payload$?.partnerId,
    "start": payload$?.start,
    "tenantId": payload$?.tenantId,
    "timezone": payload$?.timezone,
  });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "retrievePartnerAnalytics",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    RetrievePartnerAnalyticsResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, RetrievePartnerAnalyticsResponse$zodSchema, { key: "oneOf" }),
    M.json(400, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "BadRequest",
    }),
    M.json(401, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "Unauthorized",
    }),
    M.json(403, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "Forbidden",
    }),
    M.json(404, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "NotFound",
    }),
    M.json(409, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "Conflict",
    }),
    M.json(410, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "InviteExpired",
    }),
    M.json(422, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "UnprocessableEntity",
    }),
    M.json(429, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "RateLimitExceeded",
    }),
    M.json(500, RetrievePartnerAnalyticsResponse$zodSchema, {
      key: "InternalServerError",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
