/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { DubCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  GetQRCodeRequest,
  GetQRCodeRequest$zodSchema,
  GetQRCodeResponse,
  GetQRCodeResponse$zodSchema,
} from "../models/getqrcodeop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

export enum GetAcceptEnum {
  applicationJsonAccept = "application/json",
  imagePngAccept = "image/png",
}

/**
 * Retrieve a QR code
 *
 * @remarks
 * Retrieve a QR code for a link.
 */
export function qrCodesGet(
  client$: DubCore,
  request: GetQRCodeRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    GetQRCodeResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: DubCore,
  request: GetQRCodeRequest,
  options?: RequestOptions & { acceptHeaderOverride?: GetAcceptEnum },
): Promise<
  [
    Result<
      GetQRCodeResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => GetQRCodeRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/qr")();
  const query$ = encodeFormQuery({
    "bgColor": payload$.bgColor,
    "fgColor": payload$.fgColor,
    "hideLogo": payload$.hideLogo,
    "includeMargin": payload$.includeMargin,
    "level": payload$.level,
    "logo": payload$.logo,
    "margin": payload$.margin,
    "size": payload$.size,
    "url": payload$.url,
  });

  const headers$ = new Headers(compactMap({
    Accept: options?.acceptHeaderOverride
      || "application/json;q=1, image/png;q=0",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "getQRCode",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    GetQRCodeResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.text(200, GetQRCodeResponse$zodSchema, {
      ctype: "image/png",
      key: "res",
    }),
    M.json(400, GetQRCodeResponse$zodSchema, { key: "BadRequest" }),
    M.json(401, GetQRCodeResponse$zodSchema, { key: "Unauthorized" }),
    M.json(403, GetQRCodeResponse$zodSchema, { key: "Forbidden" }),
    M.json(404, GetQRCodeResponse$zodSchema, { key: "NotFound" }),
    M.json(409, GetQRCodeResponse$zodSchema, { key: "Conflict" }),
    M.json(410, GetQRCodeResponse$zodSchema, { key: "InviteExpired" }),
    M.json(422, GetQRCodeResponse$zodSchema, { key: "UnprocessableEntity" }),
    M.json(429, GetQRCodeResponse$zodSchema, { key: "RateLimitExceeded" }),
    M.json(500, GetQRCodeResponse$zodSchema, { key: "InternalServerError" }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
