workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/deathstar/deathstar/petstore-oas
targets:
    petstore:
        target: mcp-typescript
        source: petstore-oas
