/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const Region$zodSchema = z.enum([
  "*",
]);

export type Region = z.infer<typeof Region$zodSchema>;

export const AnalyticsCountriesCity$zodSchema = z.enum([
  "*",
]);

export type AnalyticsCountriesCity = z.infer<
  typeof AnalyticsCountriesCity$zodSchema
>;

export type AnalyticsCountries = {
  country: string;
  region?: Region | undefined;
  city?: AnalyticsCountriesCity | undefined;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const AnalyticsCountries$zodSchema: z.ZodType<
  AnalyticsCountries,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: AnalyticsCountriesCity$zodSchema.default("*"),
  clicks: z.number().default(0),
  country: z.string(),
  leads: z.number().default(0),
  region: Region$zodSchema.default("*"),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
});
