/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of trigger method: link click or QR scan
 */
export const Trigger$zodSchema = z.enum([
  "qr",
  "link",
]).describe("The type of trigger method: link click or QR scan");

export type Trigger = z.infer<typeof Trigger$zodSchema>;

export type AnalyticsTriggers = {
  trigger: Trigger;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const AnalyticsTriggers$zodSchema: z.ZodType<
  AnalyticsTriggers,
  z.ZodTypeDef,
  unknown
> = z.object({
  clicks: z.number().default(0),
  leads: z.number().default(0),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
  trigger: Trigger$zodSchema,
});
