/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const AnalyticsRegionsCity$zodSchema = z.enum([
  "*",
]);

export type AnalyticsRegionsCity = z.infer<
  typeof AnalyticsRegionsCity$zodSchema
>;

export type AnalyticsRegions = {
  country: string;
  region: string;
  city?: AnalyticsRegionsCity | undefined;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const AnalyticsRegions$zodSchema: z.ZodType<
  AnalyticsRegions,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: AnalyticsRegionsCity$zodSchema.default("*"),
  clicks: z.number().default(0),
  country: z.string(),
  leads: z.number().default(0),
  region: z.string(),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
});
