/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnalyticsCities = {
  country: string;
  region: string;
  city: string;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const AnalyticsCities$zodSchema: z.ZodType<
  AnalyticsCities,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: z.string(),
  clicks: z.number().default(0),
  country: z.string(),
  leads: z.number().default(0),
  region: z.string(),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
});
