/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnalyticsBrowsers = {
  browser: string;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const AnalyticsBrowsers$zodSchema: z.ZodType<
  AnalyticsBrowsers,
  z.ZodTypeDef,
  unknown
> = z.object({
  browser: z.string(),
  clicks: z.number().default(0),
  leads: z.number().default(0),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
});
