/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The 2-letter ISO 3166-1 code representing the continent associated with the location of the user.
 */
export const Continent$zodSchema = z.enum([
  "AF",
  "AN",
  "AS",
  "EU",
  "NA",
  "OC",
  "SA",
]).describe(
  "The 2-letter ISO 3166-1 code representing the continent associated with the location of the user.",
);

export type Continent = z.infer<typeof Continent$zodSchema>;

export type AnalyticsContinents = {
  continent: Continent;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const AnalyticsContinents$zodSchema: z.ZodType<
  AnalyticsContinents,
  z.ZodTypeDef,
  unknown
> = z.object({
  clicks: z.number().default(0),
  continent: Continent$zodSchema,
  leads: z.number().default(0),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
});
