/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A short code indicating the error code returned.
 */
export const BadRequestCode$zodSchema = z.enum([
  "bad_request",
]).describe("A short code indicating the error code returned.");

export type BadRequestCode = z.infer<typeof BadRequestCode$zodSchema>;

export type BadRequestError = {
  code: BadRequestCode;
  message: string;
  doc_url?: string | undefined;
};

export const BadRequestError$zodSchema: z.ZodType<
  BadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: BadRequestCode$zodSchema,
  doc_url: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
 */
export type BadRequest = { error: BadRequestError };

export const BadRequest$zodSchema: z.ZodType<
  BadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => BadRequestError$zodSchema),
}).describe(
  "The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).",
);
