/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The continent to retrieve analytics for.
 */
export const ContinentCode$zodSchema = z.enum([
  "AF",
  "AN",
  "AS",
  "EU",
  "NA",
  "OC",
  "SA",
]).describe("The continent to retrieve analytics for.");

export type ContinentCode = z.infer<typeof ContinentCode$zodSchema>;
