/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { InviteExpired, InviteExpired$zodSchema } from "./inviteexpired.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  RateLimitExceeded,
  RateLimitExceeded$zodSchema,
} from "./ratelimitexceeded.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type CreateCustomerRequest = {
  email?: string | null | undefined;
  name?: string | null | undefined;
  avatar?: string | null | undefined;
  externalId: string;
};

export const CreateCustomerRequest$zodSchema: z.ZodType<
  CreateCustomerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  avatar: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  externalId: z.string(),
  name: z.string().nullable().optional(),
});

export type CreateCustomerLink = {
  id: string;
  domain: string;
  key: string;
  shortLink: string;
  url: string;
  programId: string | null;
};

export const CreateCustomerLink$zodSchema: z.ZodType<
  CreateCustomerLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  id: z.string(),
  key: z.string(),
  programId: z.string().nullable(),
  shortLink: z.string(),
  url: z.string(),
});

export type CreateCustomerPartner = {
  id: string;
  name: string;
  email: string | null;
  image: string | null;
};

export const CreateCustomerPartner$zodSchema: z.ZodType<
  CreateCustomerPartner,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().nullable(),
  id: z.string(),
  image: z.string().nullable(),
  name: z.string(),
});

export const CreateCustomerType$zodSchema = z.enum([
  "percentage",
  "flat",
]);

export type CreateCustomerType = z.infer<typeof CreateCustomerType$zodSchema>;

export type CreateCustomerDiscount = {
  id: string;
  amount: number;
  type: CreateCustomerType;
  maxDuration: number | null;
  description?: string | null | undefined;
  couponId: string | null;
  couponTestId: string | null;
  partnersCount?: number | null | undefined;
};

export const CreateCustomerDiscount$zodSchema: z.ZodType<
  CreateCustomerDiscount,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number(),
  couponId: z.string().nullable(),
  couponTestId: z.string().nullable(),
  description: z.string().nullable().optional(),
  id: z.string(),
  maxDuration: z.number().nullable(),
  partnersCount: z.number().nullable().optional(),
  type: CreateCustomerType$zodSchema,
});

/**
 * The customer was created.
 */
export type CreateCustomerResponseBody = {
  id: string;
  externalId: string;
  name: string;
  email?: string | null | undefined;
  avatar?: string | null | undefined;
  country?: string | null | undefined;
  sales?: number | null | undefined;
  saleAmount?: number | null | undefined;
  createdAt: string;
  link?: CreateCustomerLink | null | undefined;
  programId?: string | null | undefined;
  partner?: CreateCustomerPartner | null | undefined;
  discount?: CreateCustomerDiscount | null | undefined;
};

export const CreateCustomerResponseBody$zodSchema: z.ZodType<
  CreateCustomerResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  avatar: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  createdAt: z.string(),
  discount: z.lazy(() => CreateCustomerDiscount$zodSchema).nullable()
    .optional(),
  email: z.string().nullable().optional(),
  externalId: z.string(),
  id: z.string(),
  link: z.lazy(() => CreateCustomerLink$zodSchema).nullable().optional(),
  name: z.string(),
  partner: z.lazy(() => CreateCustomerPartner$zodSchema).nullable().optional(),
  programId: z.string().nullable().optional(),
  saleAmount: z.number().nullable().optional(),
  sales: z.number().nullable().optional(),
}).describe("The customer was created.");

export type CreateCustomerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CreateCustomerResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  Conflict?: Conflict | undefined;
  InviteExpired?: InviteExpired | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  RateLimitExceeded?: RateLimitExceeded | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreateCustomerResponse$zodSchema: z.ZodType<
  CreateCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  Conflict: Conflict$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  InviteExpired: InviteExpired$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RateLimitExceeded: RateLimitExceeded$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => CreateCustomerResponseBody$zodSchema).optional(),
});
