/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { InviteExpired, InviteExpired$zodSchema } from "./inviteexpired.js";
import { LinkSchema, LinkSchema$zodSchema } from "./linkschema.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  RateLimitExceeded,
  RateLimitExceeded$zodSchema,
} from "./ratelimitexceeded.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

/**
 * The unique IDs of the tags assigned to the short link.
 */
export type CreatePartnerLinkTagIds = string | Array<string>;

export const CreatePartnerLinkTagIds$zodSchema: z.ZodType<
  CreatePartnerLinkTagIds,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.array(z.string()),
]).describe("The unique IDs of the tags assigned to the short link.");

/**
 * The unique name of the tags assigned to the short link (case insensitive).
 */
export type CreatePartnerLinkTagNames = string | Array<string>;

export const CreatePartnerLinkTagNames$zodSchema: z.ZodType<
  CreatePartnerLinkTagNames,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.array(z.string()),
]).describe(
  "The unique name of the tags assigned to the short link (case insensitive).",
);

export type CreatePartnerLinkTestVariant = { url: string; percentage: number };

export const CreatePartnerLinkTestVariant$zodSchema: z.ZodType<
  CreatePartnerLinkTestVariant,
  z.ZodTypeDef,
  unknown
> = z.object({
  percentage: z.number(),
  url: z.string(),
});

/**
 * Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.
 */
export type CreatePartnerLinkLinkProps = {
  keyLength?: number | undefined;
  externalId?: string | null | undefined;
  tenantId?: string | null | undefined;
  prefix?: string | undefined;
  archived?: boolean | undefined;
  tagIds?: string | Array<string> | undefined;
  tagNames?: string | Array<string> | undefined;
  folderId?: string | null | undefined;
  comments?: string | null | undefined;
  expiresAt?: string | null | undefined;
  expiredUrl?: string | null | undefined;
  password?: string | null | undefined;
  proxy?: boolean | undefined;
  title?: string | null | undefined;
  description?: string | null | undefined;
  image?: string | null | undefined;
  video?: string | null | undefined;
  rewrite?: boolean | undefined;
  ios?: string | null | undefined;
  android?: string | null | undefined;
  doIndex?: boolean | undefined;
  utm_source?: string | null | undefined;
  utm_medium?: string | null | undefined;
  utm_campaign?: string | null | undefined;
  utm_term?: string | null | undefined;
  utm_content?: string | null | undefined;
  ref?: string | null | undefined;
  testVariants?: Array<CreatePartnerLinkTestVariant> | null | undefined;
  testStartedAt?: string | null | undefined;
  testCompletedAt?: string | null | undefined;
};

export const CreatePartnerLinkLinkProps$zodSchema: z.ZodType<
  CreatePartnerLinkLinkProps,
  z.ZodTypeDef,
  unknown
> = z.object({
  android: z.string().nullable().optional(),
  archived: z.boolean().optional(),
  comments: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  doIndex: z.boolean().optional(),
  expiredUrl: z.string().nullable().optional(),
  expiresAt: z.string().nullable().optional(),
  externalId: z.string().nullable().optional(),
  folderId: z.string().nullable().optional(),
  image: z.string().nullable().optional(),
  ios: z.string().nullable().optional(),
  keyLength: z.number().optional(),
  password: z.string().nullable().optional(),
  prefix: z.string().optional(),
  proxy: z.boolean().optional(),
  ref: z.string().nullable().optional(),
  rewrite: z.boolean().optional(),
  tagIds: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  tagNames: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  tenantId: z.string().nullable().optional(),
  testCompletedAt: z.string().nullable().optional(),
  testStartedAt: z.string().nullable().optional(),
  testVariants: z.array(z.lazy(() => CreatePartnerLinkTestVariant$zodSchema))
    .nullable().optional(),
  title: z.string().nullable().optional(),
  utm_campaign: z.string().nullable().optional(),
  utm_content: z.string().nullable().optional(),
  utm_medium: z.string().nullable().optional(),
  utm_source: z.string().nullable().optional(),
  utm_term: z.string().nullable().optional(),
  video: z.string().nullable().optional(),
}).describe(
  "Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.",
);

export type CreatePartnerLinkRequest = {
  partnerId?: string | null | undefined;
  tenantId?: string | null | undefined;
  url?: string | null | undefined;
  key?: string | undefined;
  comments?: string | null | undefined;
  linkProps?: CreatePartnerLinkLinkProps | undefined;
};

export const CreatePartnerLinkRequest$zodSchema: z.ZodType<
  CreatePartnerLinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  comments: z.string().nullable().optional(),
  key: z.string().optional(),
  linkProps: z.lazy(() => CreatePartnerLinkLinkProps$zodSchema).optional(),
  partnerId: z.string().nullable().optional(),
  tenantId: z.string().nullable().optional(),
  url: z.string().nullable().optional(),
});

export type CreatePartnerLinkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  LinkSchema?: LinkSchema | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  Conflict?: Conflict | undefined;
  InviteExpired?: InviteExpired | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  RateLimitExceeded?: RateLimitExceeded | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreatePartnerLinkResponse$zodSchema: z.ZodType<
  CreatePartnerLinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  Conflict: Conflict$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  InviteExpired: InviteExpired$zodSchema.optional(),
  LinkSchema: LinkSchema$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RateLimitExceeded: RateLimitExceeded$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
