/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { InviteExpired, InviteExpired$zodSchema } from "./inviteexpired.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  RateLimitExceeded,
  RateLimitExceeded$zodSchema,
} from "./ratelimitexceeded.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

/**
 * The partner's country of residence. Must be passed as a 2-letter ISO 3166-1 country code. Learn more: https://d.to/geo
 */
export const CreatePartnerCountry$zodSchema = z.enum([
  "AF",
  "AL",
  "DZ",
  "AS",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BA",
  "BW",
  "BV",
  "BR",
  "IO",
  "BN",
  "BG",
  "BF",
  "BI",
  "KH",
  "CM",
  "CA",
  "CV",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CX",
  "CC",
  "CO",
  "KM",
  "CG",
  "CD",
  "CK",
  "CR",
  "CI",
  "HR",
  "CU",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GR",
  "GL",
  "GD",
  "GP",
  "GU",
  "GT",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "VA",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IL",
  "IT",
  "JM",
  "JP",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NC",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "MK",
  "MP",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "PR",
  "QA",
  "RE",
  "RO",
  "RU",
  "RW",
  "SH",
  "KN",
  "LC",
  "PM",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "SC",
  "SL",
  "SG",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "GS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SJ",
  "SZ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "US",
  "UM",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VG",
  "VI",
  "WF",
  "EH",
  "YE",
  "ZM",
  "ZW",
  "AX",
  "BQ",
  "CW",
  "GG",
  "IM",
  "JE",
  "ME",
  "BL",
  "MF",
  "RS",
  "SX",
  "SS",
  "XK",
]).describe(
  "The partner's country of residence. Must be passed as a 2-letter ISO 3166-1 country code. Learn more: https://d.to/geo",
);

export type CreatePartnerCountry = z.infer<
  typeof CreatePartnerCountry$zodSchema
>;

/**
 * The unique IDs of the tags assigned to the short link.
 */
export type CreatePartnerTagIds = string | Array<string>;

export const CreatePartnerTagIds$zodSchema: z.ZodType<
  CreatePartnerTagIds,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.array(z.string()),
]).describe("The unique IDs of the tags assigned to the short link.");

/**
 * The unique name of the tags assigned to the short link (case insensitive).
 */
export type CreatePartnerTagNames = string | Array<string>;

export const CreatePartnerTagNames$zodSchema: z.ZodType<
  CreatePartnerTagNames,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.array(z.string()),
]).describe(
  "The unique name of the tags assigned to the short link (case insensitive).",
);

export type CreatePartnerTestVariant = { url: string; percentage: number };

export const CreatePartnerTestVariant$zodSchema: z.ZodType<
  CreatePartnerTestVariant,
  z.ZodTypeDef,
  unknown
> = z.object({
  percentage: z.number(),
  url: z.string(),
});

/**
 * Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.
 */
export type CreatePartnerLinkProps = {
  keyLength?: number | undefined;
  externalId?: string | null | undefined;
  tenantId?: string | null | undefined;
  prefix?: string | undefined;
  archived?: boolean | undefined;
  tagIds?: string | Array<string> | undefined;
  tagNames?: string | Array<string> | undefined;
  folderId?: string | null | undefined;
  comments?: string | null | undefined;
  expiresAt?: string | null | undefined;
  expiredUrl?: string | null | undefined;
  password?: string | null | undefined;
  proxy?: boolean | undefined;
  title?: string | null | undefined;
  description?: string | null | undefined;
  image?: string | null | undefined;
  video?: string | null | undefined;
  rewrite?: boolean | undefined;
  ios?: string | null | undefined;
  android?: string | null | undefined;
  doIndex?: boolean | undefined;
  utm_source?: string | null | undefined;
  utm_medium?: string | null | undefined;
  utm_campaign?: string | null | undefined;
  utm_term?: string | null | undefined;
  utm_content?: string | null | undefined;
  ref?: string | null | undefined;
  testVariants?: Array<CreatePartnerTestVariant> | null | undefined;
  testStartedAt?: string | null | undefined;
  testCompletedAt?: string | null | undefined;
};

export const CreatePartnerLinkProps$zodSchema: z.ZodType<
  CreatePartnerLinkProps,
  z.ZodTypeDef,
  unknown
> = z.object({
  android: z.string().nullable().optional(),
  archived: z.boolean().optional(),
  comments: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  doIndex: z.boolean().optional(),
  expiredUrl: z.string().nullable().optional(),
  expiresAt: z.string().nullable().optional(),
  externalId: z.string().nullable().optional(),
  folderId: z.string().nullable().optional(),
  image: z.string().nullable().optional(),
  ios: z.string().nullable().optional(),
  keyLength: z.number().optional(),
  password: z.string().nullable().optional(),
  prefix: z.string().optional(),
  proxy: z.boolean().optional(),
  ref: z.string().nullable().optional(),
  rewrite: z.boolean().optional(),
  tagIds: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  tagNames: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  tenantId: z.string().nullable().optional(),
  testCompletedAt: z.string().nullable().optional(),
  testStartedAt: z.string().nullable().optional(),
  testVariants: z.array(z.lazy(() => CreatePartnerTestVariant$zodSchema))
    .nullable().optional(),
  title: z.string().nullable().optional(),
  utm_campaign: z.string().nullable().optional(),
  utm_content: z.string().nullable().optional(),
  utm_medium: z.string().nullable().optional(),
  utm_source: z.string().nullable().optional(),
  utm_term: z.string().nullable().optional(),
  video: z.string().nullable().optional(),
}).describe(
  "Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.",
);

export type CreatePartnerRequest = {
  name?: string | null | undefined;
  email: string;
  username?: string | null | undefined;
  image?: string | null | undefined;
  tenantId?: string | undefined;
  country?: CreatePartnerCountry | null | undefined;
  description?: string | null | undefined;
  linkProps?: CreatePartnerLinkProps | undefined;
};

export const CreatePartnerRequest$zodSchema: z.ZodType<
  CreatePartnerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  country: CreatePartnerCountry$zodSchema.nullable().optional(),
  description: z.string().nullable().optional(),
  email: z.string(),
  image: z.string().nullable().optional(),
  linkProps: z.lazy(() => CreatePartnerLinkProps$zodSchema).optional(),
  name: z.string().nullable().optional(),
  tenantId: z.string().optional(),
  username: z.string().nullable().optional(),
});

/**
 * The status of the partner's enrollment in the program.
 */
export const CreatePartnerStatus$zodSchema = z.enum([
  "pending",
  "approved",
  "rejected",
  "invited",
  "declined",
  "banned",
  "archived",
]).describe("The status of the partner's enrollment in the program.");

export type CreatePartnerStatus = z.infer<typeof CreatePartnerStatus$zodSchema>;

export type CreatePartnerLink = {
  id: string;
  domain: string;
  key: string;
  shortLink: string;
  url: string;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const CreatePartnerLink$zodSchema: z.ZodType<
  CreatePartnerLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  clicks: z.number().default(0),
  domain: z.string(),
  id: z.string(),
  key: z.string(),
  leads: z.number().default(0),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
  shortLink: z.string(),
  url: z.string(),
});

/**
 * The created partner
 */
export type CreatePartnerResponseBody = {
  id: string;
  name: string;
  email: string | null;
  image: string | null;
  description?: string | null | undefined;
  country: string | null;
  website: string | null;
  youtube: string | null;
  twitter: string | null;
  linkedin: string | null;
  instagram: string | null;
  tiktok: string | null;
  paypalEmail: string | null;
  stripeConnectId: string | null;
  payoutsEnabledAt: string | null;
  createdAt: string;
  status: CreatePartnerStatus;
  programId: string;
  tenantId: string | null;
  links: Array<CreatePartnerLink> | null;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
  totalCommissions?: number | undefined;
  netRevenue?: number | undefined;
  earnings?: number | undefined;
};

export const CreatePartnerResponseBody$zodSchema: z.ZodType<
  CreatePartnerResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  clicks: z.number().default(0),
  country: z.string().nullable(),
  createdAt: z.string(),
  description: z.string().nullable().optional(),
  earnings: z.number().default(0),
  email: z.string().nullable(),
  id: z.string(),
  image: z.string().nullable(),
  instagram: z.string().nullable(),
  leads: z.number().default(0),
  linkedin: z.string().nullable(),
  links: z.array(z.lazy(() => CreatePartnerLink$zodSchema)).nullable(),
  name: z.string(),
  netRevenue: z.number().default(0),
  payoutsEnabledAt: z.string().nullable(),
  paypalEmail: z.string().nullable(),
  programId: z.string(),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
  status: CreatePartnerStatus$zodSchema,
  stripeConnectId: z.string().nullable(),
  tenantId: z.string().nullable(),
  tiktok: z.string().nullable(),
  totalCommissions: z.number().default(0),
  twitter: z.string().nullable(),
  website: z.string().nullable(),
  youtube: z.string().nullable(),
}).describe("The created partner");

export type CreatePartnerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CreatePartnerResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  Conflict?: Conflict | undefined;
  InviteExpired?: InviteExpired | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  RateLimitExceeded?: RateLimitExceeded | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const CreatePartnerResponse$zodSchema: z.ZodType<
  CreatePartnerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  Conflict: Conflict$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  InviteExpired: InviteExpired$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RateLimitExceeded: RateLimitExceeded$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => CreatePartnerResponseBody$zodSchema).optional(),
});
