/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const Type$zodSchema = z.enum([
  "default",
  "mega",
]);

export type Type = z.infer<typeof Type$zodSchema>;

/**
 * The access level of the folder within the workspace.
 */
export const AccessLevel$zodSchema = z.enum([
  "write",
  "read",
]).describe("The access level of the folder within the workspace.");

export type AccessLevel = z.infer<typeof AccessLevel$zodSchema>;

export type FolderSchema = {
  id: string;
  name: string;
  type: Type;
  accessLevel?: AccessLevel | null | undefined;
  createdAt: string;
  updatedAt: string;
};

export const FolderSchema$zodSchema: z.ZodType<
  FolderSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessLevel: AccessLevel$zodSchema.nullable().default(null),
  createdAt: z.string(),
  id: z.string(),
  name: z.string(),
  type: Type$zodSchema,
  updatedAt: z.string(),
});
