/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`.
 */
export type LinkGeoTargeting = {
  AF?: string | undefined;
  AL?: string | undefined;
  DZ?: string | undefined;
  AS?: string | undefined;
  AD?: string | undefined;
  AO?: string | undefined;
  AI?: string | undefined;
  AQ?: string | undefined;
  AG?: string | undefined;
  AR?: string | undefined;
  AM?: string | undefined;
  AW?: string | undefined;
  AU?: string | undefined;
  AT?: string | undefined;
  AZ?: string | undefined;
  BS?: string | undefined;
  BH?: string | undefined;
  BD?: string | undefined;
  BB?: string | undefined;
  BY?: string | undefined;
  BE?: string | undefined;
  BZ?: string | undefined;
  BJ?: string | undefined;
  BM?: string | undefined;
  BT?: string | undefined;
  BO?: string | undefined;
  BA?: string | undefined;
  BW?: string | undefined;
  BV?: string | undefined;
  BR?: string | undefined;
  IO?: string | undefined;
  BN?: string | undefined;
  BG?: string | undefined;
  BF?: string | undefined;
  BI?: string | undefined;
  KH?: string | undefined;
  CM?: string | undefined;
  CA?: string | undefined;
  CV?: string | undefined;
  KY?: string | undefined;
  CF?: string | undefined;
  TD?: string | undefined;
  CL?: string | undefined;
  CN?: string | undefined;
  CX?: string | undefined;
  CC?: string | undefined;
  CO?: string | undefined;
  KM?: string | undefined;
  CG?: string | undefined;
  CD?: string | undefined;
  CK?: string | undefined;
  CR?: string | undefined;
  CI?: string | undefined;
  HR?: string | undefined;
  CU?: string | undefined;
  CY?: string | undefined;
  CZ?: string | undefined;
  DK?: string | undefined;
  DJ?: string | undefined;
  DM?: string | undefined;
  DO?: string | undefined;
  EC?: string | undefined;
  EG?: string | undefined;
  SV?: string | undefined;
  GQ?: string | undefined;
  ER?: string | undefined;
  EE?: string | undefined;
  ET?: string | undefined;
  FK?: string | undefined;
  FO?: string | undefined;
  FJ?: string | undefined;
  FI?: string | undefined;
  FR?: string | undefined;
  GF?: string | undefined;
  PF?: string | undefined;
  TF?: string | undefined;
  GA?: string | undefined;
  GM?: string | undefined;
  GE?: string | undefined;
  DE?: string | undefined;
  GH?: string | undefined;
  GI?: string | undefined;
  GR?: string | undefined;
  GL?: string | undefined;
  GD?: string | undefined;
  GP?: string | undefined;
  GU?: string | undefined;
  GT?: string | undefined;
  GN?: string | undefined;
  GW?: string | undefined;
  GY?: string | undefined;
  HT?: string | undefined;
  HM?: string | undefined;
  VA?: string | undefined;
  HN?: string | undefined;
  HK?: string | undefined;
  HU?: string | undefined;
  IS?: string | undefined;
  IN?: string | undefined;
  ID?: string | undefined;
  IR?: string | undefined;
  IQ?: string | undefined;
  IE?: string | undefined;
  IL?: string | undefined;
  IT?: string | undefined;
  JM?: string | undefined;
  JP?: string | undefined;
  JO?: string | undefined;
  KZ?: string | undefined;
  KE?: string | undefined;
  KI?: string | undefined;
  KP?: string | undefined;
  KR?: string | undefined;
  KW?: string | undefined;
  KG?: string | undefined;
  LA?: string | undefined;
  LV?: string | undefined;
  LB?: string | undefined;
  LS?: string | undefined;
  LR?: string | undefined;
  LY?: string | undefined;
  LI?: string | undefined;
  LT?: string | undefined;
  LU?: string | undefined;
  MO?: string | undefined;
  MG?: string | undefined;
  MW?: string | undefined;
  MY?: string | undefined;
  MV?: string | undefined;
  ML?: string | undefined;
  MT?: string | undefined;
  MH?: string | undefined;
  MQ?: string | undefined;
  MR?: string | undefined;
  MU?: string | undefined;
  YT?: string | undefined;
  MX?: string | undefined;
  FM?: string | undefined;
  MD?: string | undefined;
  MC?: string | undefined;
  MN?: string | undefined;
  MS?: string | undefined;
  MA?: string | undefined;
  MZ?: string | undefined;
  MM?: string | undefined;
  NA?: string | undefined;
  NR?: string | undefined;
  NP?: string | undefined;
  NL?: string | undefined;
  NC?: string | undefined;
  NZ?: string | undefined;
  NI?: string | undefined;
  NE?: string | undefined;
  NG?: string | undefined;
  NU?: string | undefined;
  NF?: string | undefined;
  MK?: string | undefined;
  MP?: string | undefined;
  NO?: string | undefined;
  OM?: string | undefined;
  PK?: string | undefined;
  PW?: string | undefined;
  PS?: string | undefined;
  PA?: string | undefined;
  PG?: string | undefined;
  PY?: string | undefined;
  PE?: string | undefined;
  PH?: string | undefined;
  PN?: string | undefined;
  PL?: string | undefined;
  PT?: string | undefined;
  PR?: string | undefined;
  QA?: string | undefined;
  RE?: string | undefined;
  RO?: string | undefined;
  RU?: string | undefined;
  RW?: string | undefined;
  SH?: string | undefined;
  KN?: string | undefined;
  LC?: string | undefined;
  PM?: string | undefined;
  VC?: string | undefined;
  WS?: string | undefined;
  SM?: string | undefined;
  ST?: string | undefined;
  SA?: string | undefined;
  SN?: string | undefined;
  SC?: string | undefined;
  SL?: string | undefined;
  SG?: string | undefined;
  SK?: string | undefined;
  SI?: string | undefined;
  SB?: string | undefined;
  SO?: string | undefined;
  ZA?: string | undefined;
  GS?: string | undefined;
  ES?: string | undefined;
  LK?: string | undefined;
  SD?: string | undefined;
  SR?: string | undefined;
  SJ?: string | undefined;
  SZ?: string | undefined;
  SE?: string | undefined;
  CH?: string | undefined;
  SY?: string | undefined;
  TW?: string | undefined;
  TJ?: string | undefined;
  TZ?: string | undefined;
  TH?: string | undefined;
  TL?: string | undefined;
  TG?: string | undefined;
  TK?: string | undefined;
  TO?: string | undefined;
  TT?: string | undefined;
  TN?: string | undefined;
  TR?: string | undefined;
  TM?: string | undefined;
  TC?: string | undefined;
  TV?: string | undefined;
  UG?: string | undefined;
  UA?: string | undefined;
  AE?: string | undefined;
  GB?: string | undefined;
  US?: string | undefined;
  UM?: string | undefined;
  UY?: string | undefined;
  UZ?: string | undefined;
  VU?: string | undefined;
  VE?: string | undefined;
  VN?: string | undefined;
  VG?: string | undefined;
  VI?: string | undefined;
  WF?: string | undefined;
  EH?: string | undefined;
  YE?: string | undefined;
  ZM?: string | undefined;
  ZW?: string | undefined;
  AX?: string | undefined;
  BQ?: string | undefined;
  CW?: string | undefined;
  GG?: string | undefined;
  IM?: string | undefined;
  JE?: string | undefined;
  ME?: string | undefined;
  BL?: string | undefined;
  MF?: string | undefined;
  RS?: string | undefined;
  SX?: string | undefined;
  SS?: string | undefined;
  XK?: string | undefined;
};

export const LinkGeoTargeting$zodSchema: z.ZodType<
  LinkGeoTargeting,
  z.ZodTypeDef,
  unknown
> = z.object({
  AD: z.string().optional(),
  AE: z.string().optional(),
  AF: z.string().optional(),
  AG: z.string().optional(),
  AI: z.string().optional(),
  AL: z.string().optional(),
  AM: z.string().optional(),
  AO: z.string().optional(),
  AQ: z.string().optional(),
  AR: z.string().optional(),
  AS: z.string().optional(),
  AT: z.string().optional(),
  AU: z.string().optional(),
  AW: z.string().optional(),
  AX: z.string().optional(),
  AZ: z.string().optional(),
  BA: z.string().optional(),
  BB: z.string().optional(),
  BD: z.string().optional(),
  BE: z.string().optional(),
  BF: z.string().optional(),
  BG: z.string().optional(),
  BH: z.string().optional(),
  BI: z.string().optional(),
  BJ: z.string().optional(),
  BL: z.string().optional(),
  BM: z.string().optional(),
  BN: z.string().optional(),
  BO: z.string().optional(),
  BQ: z.string().optional(),
  BR: z.string().optional(),
  BS: z.string().optional(),
  BT: z.string().optional(),
  BV: z.string().optional(),
  BW: z.string().optional(),
  BY: z.string().optional(),
  BZ: z.string().optional(),
  CA: z.string().optional(),
  CC: z.string().optional(),
  CD: z.string().optional(),
  CF: z.string().optional(),
  CG: z.string().optional(),
  CH: z.string().optional(),
  CI: z.string().optional(),
  CK: z.string().optional(),
  CL: z.string().optional(),
  CM: z.string().optional(),
  CN: z.string().optional(),
  CO: z.string().optional(),
  CR: z.string().optional(),
  CU: z.string().optional(),
  CV: z.string().optional(),
  CW: z.string().optional(),
  CX: z.string().optional(),
  CY: z.string().optional(),
  CZ: z.string().optional(),
  DE: z.string().optional(),
  DJ: z.string().optional(),
  DK: z.string().optional(),
  DM: z.string().optional(),
  DO: z.string().optional(),
  DZ: z.string().optional(),
  EC: z.string().optional(),
  EE: z.string().optional(),
  EG: z.string().optional(),
  EH: z.string().optional(),
  ER: z.string().optional(),
  ES: z.string().optional(),
  ET: z.string().optional(),
  FI: z.string().optional(),
  FJ: z.string().optional(),
  FK: z.string().optional(),
  FM: z.string().optional(),
  FO: z.string().optional(),
  FR: z.string().optional(),
  GA: z.string().optional(),
  GB: z.string().optional(),
  GD: z.string().optional(),
  GE: z.string().optional(),
  GF: z.string().optional(),
  GG: z.string().optional(),
  GH: z.string().optional(),
  GI: z.string().optional(),
  GL: z.string().optional(),
  GM: z.string().optional(),
  GN: z.string().optional(),
  GP: z.string().optional(),
  GQ: z.string().optional(),
  GR: z.string().optional(),
  GS: z.string().optional(),
  GT: z.string().optional(),
  GU: z.string().optional(),
  GW: z.string().optional(),
  GY: z.string().optional(),
  HK: z.string().optional(),
  HM: z.string().optional(),
  HN: z.string().optional(),
  HR: z.string().optional(),
  HT: z.string().optional(),
  HU: z.string().optional(),
  ID: z.string().optional(),
  IE: z.string().optional(),
  IL: z.string().optional(),
  IM: z.string().optional(),
  IN: z.string().optional(),
  IO: z.string().optional(),
  IQ: z.string().optional(),
  IR: z.string().optional(),
  IS: z.string().optional(),
  IT: z.string().optional(),
  JE: z.string().optional(),
  JM: z.string().optional(),
  JO: z.string().optional(),
  JP: z.string().optional(),
  KE: z.string().optional(),
  KG: z.string().optional(),
  KH: z.string().optional(),
  KI: z.string().optional(),
  KM: z.string().optional(),
  KN: z.string().optional(),
  KP: z.string().optional(),
  KR: z.string().optional(),
  KW: z.string().optional(),
  KY: z.string().optional(),
  KZ: z.string().optional(),
  LA: z.string().optional(),
  LB: z.string().optional(),
  LC: z.string().optional(),
  LI: z.string().optional(),
  LK: z.string().optional(),
  LR: z.string().optional(),
  LS: z.string().optional(),
  LT: z.string().optional(),
  LU: z.string().optional(),
  LV: z.string().optional(),
  LY: z.string().optional(),
  MA: z.string().optional(),
  MC: z.string().optional(),
  MD: z.string().optional(),
  ME: z.string().optional(),
  MF: z.string().optional(),
  MG: z.string().optional(),
  MH: z.string().optional(),
  MK: z.string().optional(),
  ML: z.string().optional(),
  MM: z.string().optional(),
  MN: z.string().optional(),
  MO: z.string().optional(),
  MP: z.string().optional(),
  MQ: z.string().optional(),
  MR: z.string().optional(),
  MS: z.string().optional(),
  MT: z.string().optional(),
  MU: z.string().optional(),
  MV: z.string().optional(),
  MW: z.string().optional(),
  MX: z.string().optional(),
  MY: z.string().optional(),
  MZ: z.string().optional(),
  NA: z.string().optional(),
  NC: z.string().optional(),
  NE: z.string().optional(),
  NF: z.string().optional(),
  NG: z.string().optional(),
  NI: z.string().optional(),
  NL: z.string().optional(),
  NO: z.string().optional(),
  NP: z.string().optional(),
  NR: z.string().optional(),
  NU: z.string().optional(),
  NZ: z.string().optional(),
  OM: z.string().optional(),
  PA: z.string().optional(),
  PE: z.string().optional(),
  PF: z.string().optional(),
  PG: z.string().optional(),
  PH: z.string().optional(),
  PK: z.string().optional(),
  PL: z.string().optional(),
  PM: z.string().optional(),
  PN: z.string().optional(),
  PR: z.string().optional(),
  PS: z.string().optional(),
  PT: z.string().optional(),
  PW: z.string().optional(),
  PY: z.string().optional(),
  QA: z.string().optional(),
  RE: z.string().optional(),
  RO: z.string().optional(),
  RS: z.string().optional(),
  RU: z.string().optional(),
  RW: z.string().optional(),
  SA: z.string().optional(),
  SB: z.string().optional(),
  SC: z.string().optional(),
  SD: z.string().optional(),
  SE: z.string().optional(),
  SG: z.string().optional(),
  SH: z.string().optional(),
  SI: z.string().optional(),
  SJ: z.string().optional(),
  SK: z.string().optional(),
  SL: z.string().optional(),
  SM: z.string().optional(),
  SN: z.string().optional(),
  SO: z.string().optional(),
  SR: z.string().optional(),
  SS: z.string().optional(),
  ST: z.string().optional(),
  SV: z.string().optional(),
  SX: z.string().optional(),
  SY: z.string().optional(),
  SZ: z.string().optional(),
  TC: z.string().optional(),
  TD: z.string().optional(),
  TF: z.string().optional(),
  TG: z.string().optional(),
  TH: z.string().optional(),
  TJ: z.string().optional(),
  TK: z.string().optional(),
  TL: z.string().optional(),
  TM: z.string().optional(),
  TN: z.string().optional(),
  TO: z.string().optional(),
  TR: z.string().optional(),
  TT: z.string().optional(),
  TV: z.string().optional(),
  TW: z.string().optional(),
  TZ: z.string().optional(),
  UA: z.string().optional(),
  UG: z.string().optional(),
  UM: z.string().optional(),
  US: z.string().optional(),
  UY: z.string().optional(),
  UZ: z.string().optional(),
  VA: z.string().optional(),
  VC: z.string().optional(),
  VE: z.string().optional(),
  VG: z.string().optional(),
  VI: z.string().optional(),
  VN: z.string().optional(),
  VU: z.string().optional(),
  WF: z.string().optional(),
  WS: z.string().optional(),
  XK: z.string().optional(),
  YE: z.string().optional(),
  YT: z.string().optional(),
  ZA: z.string().optional(),
  ZM: z.string().optional(),
  ZW: z.string().optional(),
}).describe(
  "Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`.",
);
