/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PartnerAnalyticsTopLinks = {
  link: string;
  id: string;
  domain: string;
  key: string;
  shortLink: string;
  url: string;
  comments?: string | null | undefined;
  title?: string | null | undefined;
  createdAt: string;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
  earnings?: number | undefined;
};

export const PartnerAnalyticsTopLinks$zodSchema: z.ZodType<
  PartnerAnalyticsTopLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  clicks: z.number().default(0),
  comments: z.string().nullable().optional(),
  createdAt: z.string(),
  domain: z.string(),
  earnings: z.number().default(0),
  id: z.string(),
  key: z.string(),
  leads: z.number().default(0),
  link: z.string(),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
  shortLink: z.string(),
  title: z.string().nullable().optional(),
  url: z.string(),
});
