/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { InviteExpired, InviteExpired$zodSchema } from "./inviteexpired.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  RateLimitExceeded,
  RateLimitExceeded$zodSchema,
} from "./ratelimitexceeded.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type RetrieveLinksRequest = {
  partnerId?: string | undefined;
  tenantId?: string | undefined;
};

export const RetrieveLinksRequest$zodSchema: z.ZodType<
  RetrieveLinksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  partnerId: z.string().optional(),
  tenantId: z.string().optional(),
});

export type RetrieveLinksLink = {
  id: string;
  domain: string;
  key: string;
  shortLink: string;
  url: string;
  clicks?: number | undefined;
  leads?: number | undefined;
  sales?: number | undefined;
  saleAmount?: number | undefined;
};

export const RetrieveLinksLink$zodSchema: z.ZodType<
  RetrieveLinksLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  clicks: z.number().default(0),
  domain: z.string(),
  id: z.string(),
  key: z.string(),
  leads: z.number().default(0),
  saleAmount: z.number().default(0),
  sales: z.number().default(0),
  shortLink: z.string(),
  url: z.string(),
});

export type RetrieveLinksResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Links?: Array<RetrieveLinksLink> | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  Conflict?: Conflict | undefined;
  InviteExpired?: InviteExpired | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  RateLimitExceeded?: RateLimitExceeded | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const RetrieveLinksResponse$zodSchema: z.ZodType<
  RetrieveLinksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  Conflict: Conflict$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  InviteExpired: InviteExpired$zodSchema.optional(),
  Links: z.array(z.lazy(() => RetrieveLinksLink$zodSchema)).describe(
    "The retrieved partner links.",
  ).optional(),
  NotFound: NotFound$zodSchema.optional(),
  RateLimitExceeded: RateLimitExceeded$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
});
