/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The color of the tag.
 */
export const Color$zodSchema = z.enum([
  "red",
  "yellow",
  "green",
  "blue",
  "purple",
  "pink",
  "brown",
]).describe("The color of the tag.");

export type Color = z.infer<typeof Color$zodSchema>;

export type TagSchema = { id: string; name: string; color: Color };

export const TagSchema$zodSchema: z.ZodType<TagSchema, z.ZodTypeDef, unknown> =
  z.object({
    color: Color$zodSchema,
    id: z.string(),
    name: z.string(),
  });
