/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A short code indicating the error code returned.
 */
export const UnprocessableEntityCode$zodSchema = z.enum([
  "unprocessable_entity",
]).describe("A short code indicating the error code returned.");

export type UnprocessableEntityCode = z.infer<
  typeof UnprocessableEntityCode$zodSchema
>;

export type UnprocessableEntityError = {
  code: UnprocessableEntityCode;
  message: string;
  doc_url?: string | undefined;
};

export const UnprocessableEntityError$zodSchema: z.ZodType<
  UnprocessableEntityError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: UnprocessableEntityCode$zodSchema,
  doc_url: z.string().optional(),
  message: z.string(),
});

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type UnprocessableEntity = { error: UnprocessableEntityError };

export const UnprocessableEntity$zodSchema: z.ZodType<
  UnprocessableEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => UnprocessableEntityError$zodSchema),
}).describe(
  "The request was well-formed but was unable to be followed due to semantic errors.",
);
