/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { Forbidden, Forbidden$zodSchema } from "./forbidden.js";
import {
  InternalServerError,
  InternalServerError$zodSchema,
} from "./internalservererror.js";
import { InviteExpired, InviteExpired$zodSchema } from "./inviteexpired.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import {
  RateLimitExceeded,
  RateLimitExceeded$zodSchema,
} from "./ratelimitexceeded.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";
import {
  UnprocessableEntity,
  UnprocessableEntity$zodSchema,
} from "./unprocessableentity.js";

export type UpdateCustomerRequestBody = {
  email?: string | null | undefined;
  name?: string | null | undefined;
  avatar?: string | null | undefined;
  externalId?: string | undefined;
};

export const UpdateCustomerRequestBody$zodSchema: z.ZodType<
  UpdateCustomerRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  avatar: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  externalId: z.string().optional(),
  name: z.string().nullable().optional(),
});

export type UpdateCustomerRequest = {
  id: string;
  includeExpandedFields?: boolean | undefined;
  RequestBody?: UpdateCustomerRequestBody | undefined;
};

export const UpdateCustomerRequest$zodSchema: z.ZodType<
  UpdateCustomerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() => UpdateCustomerRequestBody$zodSchema).optional(),
  id: z.string().describe(
    "The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).",
  ),
  includeExpandedFields: z.boolean().describe(
    "Whether to include expanded fields on the customer (`link`, `partner`, `discount`).",
  ).optional(),
});

export type UpdateCustomerLink = {
  id: string;
  domain: string;
  key: string;
  shortLink: string;
  url: string;
  programId: string | null;
};

export const UpdateCustomerLink$zodSchema: z.ZodType<
  UpdateCustomerLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  id: z.string(),
  key: z.string(),
  programId: z.string().nullable(),
  shortLink: z.string(),
  url: z.string(),
});

export type UpdateCustomerPartner = {
  id: string;
  name: string;
  email: string | null;
  image: string | null;
};

export const UpdateCustomerPartner$zodSchema: z.ZodType<
  UpdateCustomerPartner,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().nullable(),
  id: z.string(),
  image: z.string().nullable(),
  name: z.string(),
});

export const UpdateCustomerType$zodSchema = z.enum([
  "percentage",
  "flat",
]);

export type UpdateCustomerType = z.infer<typeof UpdateCustomerType$zodSchema>;

export type UpdateCustomerDiscount = {
  id: string;
  amount: number;
  type: UpdateCustomerType;
  maxDuration: number | null;
  description?: string | null | undefined;
  couponId: string | null;
  couponTestId: string | null;
  partnersCount?: number | null | undefined;
};

export const UpdateCustomerDiscount$zodSchema: z.ZodType<
  UpdateCustomerDiscount,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number(),
  couponId: z.string().nullable(),
  couponTestId: z.string().nullable(),
  description: z.string().nullable().optional(),
  id: z.string(),
  maxDuration: z.number().nullable(),
  partnersCount: z.number().nullable().optional(),
  type: UpdateCustomerType$zodSchema,
});

/**
 * The customer was updated.
 */
export type UpdateCustomerResponseBody = {
  id: string;
  externalId: string;
  name: string;
  email?: string | null | undefined;
  avatar?: string | null | undefined;
  country?: string | null | undefined;
  sales?: number | null | undefined;
  saleAmount?: number | null | undefined;
  createdAt: string;
  link?: UpdateCustomerLink | null | undefined;
  programId?: string | null | undefined;
  partner?: UpdateCustomerPartner | null | undefined;
  discount?: UpdateCustomerDiscount | null | undefined;
};

export const UpdateCustomerResponseBody$zodSchema: z.ZodType<
  UpdateCustomerResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  avatar: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  createdAt: z.string(),
  discount: z.lazy(() => UpdateCustomerDiscount$zodSchema).nullable()
    .optional(),
  email: z.string().nullable().optional(),
  externalId: z.string(),
  id: z.string(),
  link: z.lazy(() => UpdateCustomerLink$zodSchema).nullable().optional(),
  name: z.string(),
  partner: z.lazy(() => UpdateCustomerPartner$zodSchema).nullable().optional(),
  programId: z.string().nullable().optional(),
  saleAmount: z.number().nullable().optional(),
  sales: z.number().nullable().optional(),
}).describe("The customer was updated.");

export type UpdateCustomerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: UpdateCustomerResponseBody | undefined;
  BadRequest?: BadRequest | undefined;
  Unauthorized?: Unauthorized | undefined;
  Forbidden?: Forbidden | undefined;
  NotFound?: NotFound | undefined;
  Conflict?: Conflict | undefined;
  InviteExpired?: InviteExpired | undefined;
  UnprocessableEntity?: UnprocessableEntity | undefined;
  RateLimitExceeded?: RateLimitExceeded | undefined;
  InternalServerError?: InternalServerError | undefined;
};

export const UpdateCustomerResponse$zodSchema: z.ZodType<
  UpdateCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequest: BadRequest$zodSchema.optional(),
  Conflict: Conflict$zodSchema.optional(),
  ContentType: z.string(),
  Forbidden: Forbidden$zodSchema.optional(),
  InternalServerError: InternalServerError$zodSchema.optional(),
  InviteExpired: InviteExpired$zodSchema.optional(),
  NotFound: NotFound$zodSchema.optional(),
  RateLimitExceeded: RateLimitExceeded$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Unauthorized: Unauthorized$zodSchema.optional(),
  UnprocessableEntity: UnprocessableEntity$zodSchema.optional(),
  object: z.lazy(() => UpdateCustomerResponseBody$zodSchema).optional(),
});
