/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LeadCreatedEvent,
  LeadCreatedEvent$zodSchema,
} from "./leadcreatedevent.js";
import {
  LinkClickedEvent,
  LinkClickedEvent$zodSchema,
} from "./linkclickedevent.js";
import {
  LinkWebhookEvent,
  LinkWebhookEvent$zodSchema,
} from "./linkwebhookevent.js";
import {
  PartnerEnrolledEvent,
  PartnerEnrolledEvent$zodSchema,
} from "./partnerenrolledevent.js";
import {
  SaleCreatedEvent,
  SaleCreatedEvent$zodSchema,
} from "./salecreatedevent.js";

/**
 * Webhook event schema
 */
export type WebhookEvent =
  | LinkWebhookEvent
  | LinkClickedEvent
  | LeadCreatedEvent
  | SaleCreatedEvent
  | PartnerEnrolledEvent;

export const WebhookEvent$zodSchema: z.ZodType<
  WebhookEvent,
  z.ZodTypeDef,
  unknown
> = z.union([
  LinkWebhookEvent$zodSchema,
  LinkClickedEvent$zodSchema,
  LeadCreatedEvent$zodSchema,
  SaleCreatedEvent$zodSchema,
  PartnerEnrolledEvent$zodSchema,
]).describe("Webhook event schema");
